### ISSUE TITLE
JLCPCB Files are corrupted

### ISSUE THREAD

**Issue by DevFelixLiS** [CyberPit/FreeDSP_Classic_SMD_AB_plus-II#2]
When uploading `FreeDSP_SMD_AB_plus_0v2_BOM1` and `FreeDSP_SMD_AB_plus_0v2-CPL1`, i'm getting to the next page. Unfortunattly, the parts of the PCB are misplaced. When trying `FreeDSP_SMD_AB_plus_BOM1` and `FreeDSP_SMD_AB_plus-top-CPL1`, JLCPCB is throwing the following Error: `File processing failed, please check your file and upload again.`

**Comment by CyberPit** [comment]
Thanks for notifying the errors.
The offset-adjusted Gerber file was uploaded.

CyberPit
